name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build (opcional)
        run: |
          # si usas un generador (como npm run build), hazlo aquí
          echo "Nada que compilar"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sena/Calculadora  # cambia esto por la carpeta que quieres publicar
